services:
  ynlo.pjax.listener:
      class: YnloFramework\YnloPjaxBundle\EventListener\PjaxListener
      calls:
          - [ setContainer, [ '@service_container' ]]
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1 }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }