services:
    ynlo_admin.twig_action_test:
        class: YnloFramework\YnloAdminBundle\Twig\Tests\AdminActionTest
        tags:
            - { name: twig.extension }

    ynlo_admin.list_details_extension:
        class: YnloFramework\YnloAdminBundle\Extension\AdminListDetailsExtension
        tags:
          - { name: 'sonata.admin.extension', global: true }

    ynlo_admin.list_details_field_builder:
        class: YnloFramework\YnloAdminBundle\Builder\ListDetailsFieldBuilder
        tags:
          - { name: 'ynlo.admin.list_field_builder' }

    ynlo_admin.list_enum_field_builder:
        class: YnloFramework\YnloAdminBundle\Builder\ListEnumFieldBuilder
        tags:
          - { name: 'ynlo.admin.list_field_builder' }

    ynlo_admin.list_collection_field_builder:
        class: YnloFramework\YnloAdminBundle\Builder\ListCollectionFieldBuilder
        tags:
          - { name: 'ynlo.admin.list_field_builder' }

    ynlo_admin.list_enum_action_builder:
        class: YnloFramework\YnloAdminBundle\Builder\ListActionFieldBuilder
        tags:
            - { name: 'ynlo.admin.list_field_builder' }
        calls:
            - ['setTwig', ['@twig']]

    sonata.admin.builder.orm_list:
        class: YnloFramework\YnloAdminBundle\Builder\ListBuilder
        arguments: ['@sonata.admin.guesser.orm_list_chain', '%sonata_doctrine_orm_admin.templates%']
        calls:
            - ['setTaggedServices', ['@ynlo.tagged_services']]