services:
  rafrsr_toggle_form_extension:
      class: YnloFramework\YnloFormBundle\Form\Extension\ToggleFormTypeExtension
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  rafrsr_widget_template_form_extension:
      class: YnloFramework\YnloFormBundle\Form\Extension\WidgetTemplateExtension
      arguments: ['@templating']
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  rafrsr_form.angular_controller_form_type:
      class: YnloFramework\YnloFormBundle\Form\Type\AngularControllerType
      arguments: ['@templating']
      tags:
          - { name: form.type }

  rafrsr_form.angular_extension:
      class: YnloFramework\YnloFormBundle\Form\Extension\AngularModelExtension
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  rafrsr_select2_extension:
      class: YnloFramework\YnloFormBundle\Form\Extension\Select2Extension
      arguments: ['@templating', '@?doctrine', '%ynlo.form.confing%']
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

  rafrsr_form.autocomplete.typeahead_extension:
      class: YnloFramework\YnloFormBundle\Form\Extension\TypeaheadExtension
      calls:
          - [ setContainer, [ '@service_container' ]]
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

  rafrsr_form.autocomplete.select2_extension:
      class: YnloFramework\YnloFormBundle\Form\Extension\Select2AutocompleteExtension
      calls:
          - [ setContainer, [ '@service_container' ]]
      tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

  ynlo.form.autocomplete.provider.entity:
      class: YnloFramework\YnloFormBundle\Autocomplete\Provider\SimpleEntityProvider
      arguments: ['@?doctrine']
      tags:
          - { name: ynlo.form.autocomplete.provider }

  ynlo.form.autocomplete.provider.select2:
      class: YnloFramework\YnloFormBundle\Autocomplete\Provider\Select2Provider
      arguments: ['@?doctrine']
      calls:
           - [ setContainer, [ '@service_container' ]]
      tags:
           - { name: ynlo.form.autocomplete.provider }

  ynlo.form.autocomplete.provider.select2_tags:
      class: YnloFramework\YnloFormBundle\Autocomplete\Provider\Select2TagsProvider
      arguments: ['@?doctrine']
      tags:
          - { name: ynlo.form.autocomplete.provider }

  ynlo.form.autocomplete.provider.typeahead:
      class: YnloFramework\YnloFormBundle\Autocomplete\Provider\TypeaheadProvider
      arguments: ['@?doctrine']
      tags:
          - { name: ynlo.form.autocomplete.provider }

  ynlo.form.autocomplete.provider_manager:
      class: YnloFramework\YnloFormBundle\Autocomplete\AutocompleteProviderManager

  ynlo.form.autocomplete.context_manager:
      class: YnloFramework\YnloFormBundle\Autocomplete\AutocompleteContextManager
      arguments: ['@session']

  ynlo.form.form_type.embedded:
      class: YnloFramework\YnloFormBundle\Form\Type\EmbeddedTemplateType
      arguments: ['@templating']
      tags:
          - { name: form.type }

  rafrsr_datepicker_type_guesser:
      class: YnloFramework\YnloFormBundle\Form\Guesser\DatePickerTypeGuesser
      arguments: ['@doctrine']
      tags:
          - { name: form.type_guesser }

  rafrsr_switchery_type_guesser:
      class: YnloFramework\YnloFormBundle\Form\Guesser\SwitcheryTypeGuesser
      arguments: ['@doctrine']
      tags:
          - { name: form.type_guesser }